require('dotenv').config();
const express=require('express');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {Pool}=require('pg');
const helmet=require('helmet');
const cors=require('cors');
const multer=require('multer');

const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.APP_ORIGIN||true,credentials:false}));
const buckets=new Map();
function simpleRateLimit(max,windowMs){return (req,res,next)=>{const key=(req.ip||'unknown')+'|'+req.path;const now=Date.now();let b=buckets.get(key);if(!b||now-b.start>windowMs)b={start:now,count:0};b.count++;buckets.set(key,b);if(b.count>max)return res.status(429).json({error:'Too many requests. Please try again later.'});next();};}
app.use('/api',simpleRateLimit(240,60*1000));
const loginLimiter=simpleRateLimit(20,15*60*1000);
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true,limit:'2mb'}));

const PORT=Number(process.env.PORT||3000);
const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const DATABASE_URL=process.env.DATABASE_URL||'postgres://crm:crm_password@localhost:5432/private_contact_crm';
if(process.env.NODE_ENV==='production' && (!process.env.JWT_SECRET || process.env.JWT_SECRET==='dev-secret-change-me')){throw new Error('JWT_SECRET must be configured in production');}
const pool=new Pool({connectionString:DATABASE_URL,connectionTimeoutMillis:5000});
const uploadDir=path.resolve(process.env.UPLOAD_DIR||path.join(__dirname,'uploads'));
fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:5*1024*1024}});

const VALID_ROLES=['OWNER_ADMIN','DATA_ENTRY','RESTRICTED_VIEWER','MANAGER_VIEWER'];
const VALID_RELATIONSHIPS=['NOT_CONTACTED','CONNECTED','COMMUNICATION_STARTED','IN_TOUCH','CONSISTENT_RELATIONSHIP','STRONG_CONNECTION','DORMANT','DO_NOT_CONTACT'];
const VALID_LIFECYCLES=['DRAFT','PENDING_REVIEW','APPROVED','ACTIVE','DORMANT','ARCHIVED'];
const VALID_PRIORITIES=['LOW','NORMAL','HIGH','CRITICAL'];
const VALID_CHANNELS=['MOBILE','EMAIL','WHATSAPP','LANDLINE','LINKEDIN','WEBSITE','OTHER'];
const VALID_INTERACTION_CHANNELS=['CALL','MEETING','WHATSAPP','EMAIL','EVENT','LINKEDIN','OTHER'];
const VALID_OUTCOMES=['NO_RESPONSE','CONNECTED','INTERESTED','FOLLOW_UP_AGREED','REFERRED','NOT_INTERESTED','CLOSED'];
const VALID_TASK_STATUS=['OPEN','IN_PROGRESS','COMPLETED','CANCELLED'];

function token(user){return jwt.sign({id:user.id,email:user.email,role:user.role_code,name:user.full_name},JWT_SECRET,{expiresIn:'8h'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired session'});}}
function allow(...roles){return (req,res,next)=>{if(roles.includes(req.user.role))return next();audit(req,'ACCESS_DENIED','endpoint',req.originalUrl,{role:req.user.role});return res.status(403).json({error:'Access denied'});};}
async function audit(req,action,type,id=null,metadata={}){try{await pool.query('INSERT INTO audit_events(actor_user_id,action,resource_type,resource_id,metadata,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[req.user?.id||null,action,type,id?String(id):null,metadata,req.ip||null]);}catch(e){console.error('Audit write failed:',e.message);}}
function normalize(v,type){v=String(v||'').trim();return type==='EMAIL'?v.toLowerCase():v.replace(/[^+\d]/g,'');}
function clean(v,max=500){return typeof v==='string'?v.trim().slice(0,max):v;}
function csvCell(v){const x=String(v??'');return /[",\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x;}
function csvParse(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(ch===','&&!q){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];}else cell+=ch;}if(cell!==''||row.length){row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);}return rows;}
function requireFields(body,fields){for(const f of fields){if(body[f]===undefined||body[f]===null||String(body[f]).trim()==='')return `Missing required field: ${f}`;}return null;}
function encryptionKey(){return crypto.createHash('sha256').update(JWT_SECRET).digest();}
function encryptNote(text){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv);const enc=Buffer.concat([cipher.update(String(text),'utf8'),cipher.final()]);return `v1:${iv.toString('base64')}:${cipher.getAuthTag().toString('base64')}:${enc.toString('base64')}`;}
function decryptNote(value){try{if(!String(value).startsWith('v1:'))return value;const [,iv,tag,data]=String(value).split(':');const decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(data,'base64')),decipher.final()]).toString('utf8');}catch{return '[Private note unavailable]';}}
function base32Decode(input){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';const clean=String(input||'').toUpperCase().replace(/=+$/,'').replace(/[^A-Z2-7]/g,'');let bits='',out=[];for(const ch of clean){bits+=alphabet.indexOf(ch).toString(2).padStart(5,'0');}for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out);}
function base32Encode(buf){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const b of buf)bits+=b.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5)out+=alphabet[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out.padEnd(Math.ceil(out.length/8)*8,'=');}
function totp(secret,step=30,digits=6){const counter=Math.floor(Date.now()/1000/step);const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',base32Decode(secret)).update(msg).digest();const offset=h[h.length-1]&15;const code=((h.readUInt32BE(offset)&0x7fffffff)%10**digits).toString().padStart(digits,'0');return code;}
function verifyTotp(secret,code){const c=String(code||'').replace(/\D/g,'');if(c.length!==6)return false;const now=Math.floor(Date.now()/1000/30);for(let delta=-1;delta<=1;delta++){const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(now+delta));const h=crypto.createHmac('sha1',base32Decode(secret)).update(msg).digest();const offset=h[h.length-1]&15;const candidate=((h.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');if(crypto.timingSafeEqual(Buffer.from(candidate),Buffer.from(c)))return true;}return false;}
function newTotpSecret(){return base32Encode(crypto.randomBytes(20));}
function otpauthUri(secret,email){return `otpauth://totp/Private%20Contact%20CRM:${encodeURIComponent(email)}?secret=${secret}&issuer=Private%20Contact%20CRM&algorithm=SHA1&digits=6&period=30`;}
async function sendResetEmail(email,token){const apiKey=process.env.RESEND_API_KEY;const from=process.env.RESET_FROM_EMAIL;if(!apiKey||!from)throw new Error('Password reset email provider is not configured');const origin=(process.env.APP_ORIGIN||'').replace(/\/$/,'');if(!origin)throw new Error('APP_ORIGIN must be configured for password reset');const resetUrl=`${origin}/?reset=${encodeURIComponent(token)}`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:'Private Contact CRM password reset',html:`<p>You requested a password reset for Private Contact CRM.</p><p><a href="${resetUrl}">Reset your password</a></p><p>This link expires in 30 minutes. If you did not request this, ignore this email.</p>`})});if(!r.ok)throw new Error('Reset email could not be sent');}


async function init(){
  const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8');
  await pool.query(schema);
  const count=await pool.query('SELECT count(*)::int AS count FROM users');
  if(count.rows[0].count===0){
    const hash=await bcrypt.hash(process.env.DEFAULT_ADMIN_PASSWORD||'Admin@12345',12);
    await pool.query('INSERT INTO users(email,password_hash,full_name,role_code) VALUES($1,$2,$3,$4)',[process.env.DEFAULT_ADMIN_EMAIL||'admin@privatecrm.local',hash,process.env.DEFAULT_ADMIN_NAME||'Owner Admin','OWNER_ADMIN']);
    console.log(`Default Owner account initialized: ${process.env.DEFAULT_ADMIN_EMAIL||'admin@privatecrm.local'}`);
  }
}

app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true,uptime_seconds:Math.floor(process.uptime()),timestamp:new Date().toISOString()});}catch(e){res.status(503).json({ok:false,database:false,error:'Database unavailable',timestamp:new Date().toISOString()});}});

app.post('/api/auth/login',loginLimiter,async(req,res)=>{try{
  const email=clean(req.body.email,254)||'';const password=String(req.body.password||'');const otp=String(req.body.otp||'');
  const r=await pool.query('SELECT * FROM users WHERE lower(email)=lower($1) AND is_active=true',[email]);
  if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash))){await audit({user:null,ip:req.ip},'LOGIN_FAILED','user',null,{email});return res.status(401).json({error:'Invalid email or password'});}
  const u=r.rows[0];
  if(u.two_factor_enabled){if(!otp)return res.status(200).json({requires_2fa:true,message:'Authenticator code required'});if(!verifyTotp(decryptNote(u.two_factor_secret),otp)){await audit({user:null,ip:req.ip},'LOGIN_2FA_FAILED','user',u.id);return res.status(401).json({error:'Invalid authenticator code'});}}
  await audit({user:u,ip:req.ip},'LOGIN','user',u.id);res.json({token:token(u),user:{id:u.id,email:u.email,name:u.full_name,role:u.role_code},requires_2fa:false});
}catch(e){console.error(e);res.status(500).json({error:'Login service unavailable'});}});

app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.post('/api/auth/password-reset/request',loginLimiter,async(req,res)=>{const email=clean(req.body?.email,254).toLowerCase();if(!email)return res.status(400).json({error:'Email is required'});try{const r=await pool.query('SELECT id,email FROM users WHERE lower(email)=lower($1) AND is_active=true',[email]);if(r.rowCount){const raw=crypto.randomBytes(32).toString('hex');const hash=crypto.createHash('sha256').update(raw).digest('hex');await pool.query('UPDATE users SET password_reset_token_hash=$1,password_reset_expires_at=now()+interval \'30 minutes\' WHERE id=$2',[hash,r.rows[0].id]);await sendResetEmail(r.rows[0].email,raw);await audit({user:null,ip:req.ip},'PASSWORD_RESET_REQUEST','user',r.rows[0].id);}
res.json({ok:true,message:'If the account exists, a password reset email has been sent.'});}catch(e){console.error(e);res.status(503).json({error:'Password reset service is not configured or unavailable'});}});
app.post('/api/auth/password-reset/confirm',loginLimiter,async(req,res)=>{const tokenValue=String(req.body?.token||'');const password=String(req.body?.new_password||'');if(!tokenValue||password.length<10)return res.status(400).json({error:'Valid token and password of at least 10 characters are required'});try{const hash=crypto.createHash('sha256').update(tokenValue).digest('hex');const r=await pool.query('SELECT id FROM users WHERE password_reset_token_hash=$1 AND password_reset_expires_at>now() AND is_active=true',[hash]);if(!r.rowCount)return res.status(400).json({error:'Reset link is invalid or expired'});const ph=await bcrypt.hash(password,12);await pool.query('UPDATE users SET password_hash=$1,password_reset_token_hash=NULL,password_reset_expires_at=NULL WHERE id=$2',[ph,r.rows[0].id]);await audit({user:null,ip:req.ip},'PASSWORD_RESET_COMPLETE','user',r.rows[0].id);res.json({ok:true});}catch(e){res.status(500).json({error:'Password reset unavailable'});}});
app.post('/api/auth/2fa/setup',auth,allow('OWNER_ADMIN'),async(req,res)=>{try{const r=await pool.query('SELECT email,two_factor_enabled FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount)return res.status(404).json({error:'User not found'});if(r.rows[0].two_factor_enabled)return res.status(400).json({error:'Two-factor authentication is already enabled'});const secret=newTotpSecret();await pool.query('UPDATE users SET two_factor_secret=$1 WHERE id=$2',[encryptNote(secret),req.user.id]);await audit(req,'2FA_SETUP_STARTED','user',req.user.id);res.json({secret,otpauth_uri:otpauthUri(secret,r.rows[0].email)});}catch(e){res.status(500).json({error:'2FA setup unavailable'});}});
app.post('/api/auth/2fa/enable',auth,allow('OWNER_ADMIN'),async(req,res)=>{const code=String(req.body?.code||'');try{const r=await pool.query('SELECT two_factor_secret FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount||!r.rows[0].two_factor_secret)return res.status(400).json({error:'Start 2FA setup first'});if(!verifyTotp(decryptNote(r.rows[0].two_factor_secret),code))return res.status(400).json({error:'Invalid authenticator code'});await pool.query('UPDATE users SET two_factor_enabled=true WHERE id=$1',[req.user.id]);await audit(req,'2FA_ENABLED','user',req.user.id);res.json({ok:true});}catch(e){res.status(500).json({error:'2FA enable failed'});}});
app.post('/api/auth/2fa/disable',auth,allow('OWNER_ADMIN'),async(req,res)=>{const code=String(req.body?.code||'');try{const r=await pool.query('SELECT two_factor_secret,two_factor_enabled,password_hash FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount||!r.rows[0].two_factor_enabled)return res.status(400).json({error:'2FA is not enabled'});if(!verifyTotp(decryptNote(r.rows[0].two_factor_secret),code))return res.status(400).json({error:'Invalid authenticator code'});await pool.query('UPDATE users SET two_factor_enabled=false,two_factor_secret=NULL WHERE id=$1',[req.user.id]);await audit(req,'2FA_DISABLED','user',req.user.id);res.json({ok:true});}catch(e){res.status(500).json({error:'2FA disable failed'});}});
app.get('/api/auth/2fa/status',auth,allow('OWNER_ADMIN'),async(req,res)=>{const r=await pool.query('SELECT two_factor_enabled FROM users WHERE id=$1',[req.user.id]);res.json({enabled:!!r.rows[0]?.two_factor_enabled});});

app.post('/api/auth/change-password',auth,async(req,res)=>{const current=String(req.body?.current_password||''),next=String(req.body?.new_password||'');if(next.length<10)return res.status(400).json({error:'New password must be at least 10 characters'});try{const r=await pool.query('SELECT password_hash FROM users WHERE id=$1 AND is_active=true',[req.user.id]);if(!r.rowCount||!(await bcrypt.compare(current,r.rows[0].password_hash)))return res.status(400).json({error:'Current password is incorrect'});const hash=await bcrypt.hash(next,12);await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2',[hash,req.user.id]);await audit(req,'PASSWORD_CHANGE','user',req.user.id);res.json({ok:true});}catch(e){res.status(500).json({error:'Password update unavailable'});}});
app.post('/api/auth/logout',auth,async(req,res)=>{await audit(req,'LOGOUT','user',req.user.id);res.json({ok:true});});

app.get('/api/dashboard',auth,allow('OWNER_ADMIN','MANAGER_VIEWER'),async(req,res)=>{try{
 const metrics=(await pool.query(`SELECT
 (SELECT count(*) FROM contacts WHERE deleted_at IS NULL AND lifecycle_status<>'ARCHIVED' AND ($1='OWNER_ADMIN' OR lifecycle_status IN ('APPROVED','ACTIVE','DORMANT'))) total_contacts,
 (SELECT count(*) FROM contacts WHERE created_at>=date_trunc('month',now()) AND deleted_at IS NULL) new_this_month,
 (SELECT count(*) FROM interactions WHERE created_at>=date_trunc('month',now())) interactions_this_month,
 (SELECT count(*) FROM follow_ups WHERE status_code IN ('OPEN','IN_PROGRESS') AND due_at::date=now()::date) due_today,
 (SELECT count(*) FROM follow_ups WHERE status_code IN ('OPEN','IN_PROGRESS') AND due_at<now()) overdue,
 (SELECT count(*) FROM contacts WHERE lifecycle_status='PENDING_REVIEW' AND deleted_at IS NULL) pending_review,
 (SELECT count(*) FROM (SELECT lower(trim(c.first_name)),lower(trim(coalesce(c.last_name,''))),lower(trim(coalesce(o.name,''))) FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.deleted_at IS NULL GROUP BY 1,2,3 HAVING count(*)>1) d) duplicates`,[req.user.role])).rows[0];
 const status=(await pool.query(`SELECT relationship_status,count(*)::int count FROM contacts WHERE deleted_at IS NULL AND lifecycle_status<>'ARCHIVED' GROUP BY relationship_status ORDER BY count DESC`)).rows;
 res.json({metrics,status});
}catch(e){console.error(e);res.status(500).json({error:'Dashboard unavailable'});}});

function contactVisibility(req,alias='c'){
 const params=[];const wh=[`${alias}.deleted_at IS NULL`];
 if(req.user.role==='DATA_ENTRY') return {params:[req.user.id],wh:[`${alias}.created_by=$1 AND ${alias}.lifecycle_status='DRAFT'`]};
 else if(req.user.role==='RESTRICTED_VIEWER'){
   params.push(req.user.id);wh.push(`${alias}.lifecycle_status IN ('APPROVED','ACTIVE','DORMANT') AND (${alias}.visibility_group IS NULL OR EXISTS(SELECT 1 FROM record_access ra WHERE ra.contact_id=${alias}.id AND ra.user_id=$${params.length})) AND (${alias}.is_sensitive=false OR EXISTS(SELECT 1 FROM record_access sra WHERE sra.contact_id=${alias}.id AND sra.user_id=$${params.length}))`);
 }
 else if(req.user.role==='MANAGER_VIEWER') wh.push(`${alias}.lifecycle_status IN ('APPROVED','ACTIVE','DORMANT')`);
 return {params,wh};
}

app.get('/api/contacts/archived',auth,allow('OWNER_ADMIN'),async(req,res)=>{try{const r=await pool.query(`SELECT c.id,c.contact_code,c.first_name,c.last_name,c.category,c.relationship_status,c.deleted_at,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.deleted_at IS NOT NULL ORDER BY c.deleted_at DESC LIMIT 200`);res.json(r.rows);}catch(e){res.status(500).json({error:'Archived contacts unavailable'});}});

app.get('/api/contacts',auth,async(req,res)=>{try{
 if(req.user.role==='DATA_ENTRY') return res.status(403).json({error:'Directory access is not available for Data Entry users'});
 let page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||25));const {params,wh}=contactVisibility(req);
 const q=clean(req.query.q,200),category=clean(req.query.category,100),status=clean(req.query.status,40),priority=clean(req.query.priority,20);
 if(q){params.push('%'+q.toLowerCase()+'%');const n=params.length;wh.push(`(lower(c.first_name||' '||coalesce(c.last_name,'')) LIKE $${n} OR lower(c.contact_code) LIKE $${n} OR lower(coalesce(o.name,'')) LIKE $${n} OR EXISTS(SELECT 1 FROM contact_channels cc WHERE cc.contact_id=c.id AND lower(cc.normalized_value) LIKE $${n}))`);}
 if(category){params.push(category);wh.push(`c.category=$${params.length}`);}if(status){params.push(status);wh.push(`c.relationship_status=$${params.length}`);}if(priority){params.push(priority);wh.push(`c.priority_code=$${params.length}`);}
 const countSql=`SELECT count(*)::int count FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE ${wh.join(' AND ')}`;const total=(await pool.query(countSql,params)).rows[0].count;
 const dataParams=[...params,limit,(page-1)*limit];const r=await pool.query(`SELECT c.id,c.contact_code,c.first_name,c.last_name,c.preferred_name,c.designation,c.category,c.subcategory,c.relationship_status,c.priority_code,c.health_code,c.lifecycle_status,c.next_follow_up_at,c.do_not_contact,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE ${wh.join(' AND ')} ORDER BY c.updated_at DESC LIMIT $${dataParams.length-1} OFFSET $${dataParams.length}`,dataParams);
 res.json({items:r.rows,page,limit,total,pages:Math.max(1,Math.ceil(total/limit))});
}catch(e){console.error(e);res.status(500).json({error:'Contact search unavailable'});}});

app.post('/api/contacts/duplicate-check',auth,allow('OWNER_ADMIN','DATA_ENTRY'),async(req,res)=>{try{const x=req.body||{};const vals=[];const wh=[];if(x.mobile){vals.push(normalize(x.mobile,'MOBILE'));wh.push(`EXISTS(SELECT 1 FROM contact_channels cc WHERE cc.contact_id=c.id AND cc.normalized_value=$${vals.length})`);}if(x.email){vals.push(normalize(x.email,'EMAIL'));wh.push(`EXISTS(SELECT 1 FROM contact_channels cc WHERE cc.contact_id=c.id AND cc.normalized_value=$${vals.length})`);}if(x.first_name&&x.organization_name){vals.push(String(x.first_name).trim().toLowerCase());wh.push(`lower(trim(c.first_name))=$${vals.length}`);vals.push(String(x.organization_name).trim().toLowerCase());wh.push(`EXISTS(SELECT 1 FROM organizations o WHERE o.id=c.organization_id AND lower(trim(o.name))=$${vals.length})`);}if(!wh.length)return res.json({possible_duplicate:false});const r=await pool.query(`SELECT 1 FROM contacts c WHERE c.deleted_at IS NULL AND (${wh.join(' OR ')}) LIMIT 1`,vals);res.json({possible_duplicate:!!r.rowCount});}catch(e){res.status(500).json({error:'Duplicate check unavailable'});}});

app.post('/api/contacts/drafts',auth,allow('OWNER_ADMIN','DATA_ENTRY'),async(req,res)=>{const c=req.body||{};const missing=requireFields(c,['first_name','category']);if(missing)return res.status(400).json({error:missing});const client=await pool.connect();try{
 await client.query('BEGIN');
 let organizationId=null;if(clean(c.organization_name,200)){const org=await client.query('SELECT id FROM organizations WHERE lower(name)=lower($1) LIMIT 1',[clean(c.organization_name,200)]);if(org.rowCount)organizationId=org.rows[0].id;else {const created=await client.query('INSERT INTO organizations(name) VALUES($1) RETURNING id',[clean(c.organization_name,200)]);organizationId=created.rows[0].id;}}
 const incomingChannels=(Array.isArray(c.channels)?c.channels:[]).filter(ch=>ch&&ch.raw_value&&VALID_CHANNELS.includes(ch.channel_type)).map(ch=>({type:ch.channel_type,normalized:normalize(ch.raw_value,ch.channel_type)}));
 let duplicate=false;
 if(incomingChannels.length){const vals=incomingChannels.map(x=>x.normalized);const d=await client.query(`SELECT 1 FROM contact_channels cc JOIN contacts c2 ON c2.id=cc.contact_id WHERE c2.deleted_at IS NULL AND cc.normalized_value=ANY($1::text[]) LIMIT 1`,[vals]);duplicate=!!d.rowCount;}
 if(!duplicate && clean(c.first_name,100)){const d=await client.query(`SELECT 1 FROM contacts c2 LEFT JOIN organizations o2 ON o2.id=c2.organization_id WHERE c2.deleted_at IS NULL AND lower(trim(c2.first_name))=lower(trim($1)) AND lower(trim(coalesce(c2.last_name,'')))=lower(trim(coalesce($2,''))) AND lower(trim(coalesce(o2.name,'')))=lower(trim(coalesce($3,''))) LIMIT 1`,[clean(c.first_name,100),clean(c.last_name,100)||'',clean(c.organization_name,200)||'']);duplicate=!!d.rowCount;}
 const code='CT-'+new Date().getFullYear()+'-'+crypto.randomInt(100000,999999);
 const ownerId=req.user.role==='OWNER_ADMIN'?req.user.id:(await client.query("SELECT id FROM users WHERE role_code='OWNER_ADMIN' AND is_active=true ORDER BY created_at LIMIT 1")).rows[0]?.id||req.user.id;
 const r=await client.query(`INSERT INTO contacts(contact_code,title_code,first_name,middle_name,last_name,preferred_name,designation,department,category,subcategory,tags,source_code,source_detail,organization_id,owner_user_id,is_sensitive,relationship_status,priority_code,health_code,marketing_consent,do_not_contact,do_not_contact_reason,lifecycle_status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24) RETURNING *`,[code,c.title_code||null,clean(c.first_name,100),clean(c.middle_name,100)||null,clean(c.last_name,100)||null,clean(c.preferred_name,100)||null,clean(c.designation,150)||null,clean(c.department,150)||null,clean(c.category,100),clean(c.subcategory,100)||null,Array.isArray(c.tags)?c.tags.slice(0,50).map(x=>clean(x,80)):[],clean(c.source_code,50)||'MANUAL',clean(c.source_detail,250)||null,organizationId,ownerId,!!c.is_sensitive,'NOT_CONTACTED',VALID_PRIORITIES.includes(c.priority_code)?c.priority_code:'NORMAL',clean(c.health_code,20)||'GOOD',!!c.marketing_consent,!!c.do_not_contact,clean(c.do_not_contact_reason,250)||null,'DRAFT',req.user.id]);
 for(const ch of Array.isArray(c.channels)?c.channels:[]){if(!ch.raw_value||!VALID_CHANNELS.includes(ch.channel_type))continue;const raw=clean(ch.raw_value,300);await client.query('INSERT INTO contact_channels(contact_id,channel_type,label,raw_value,normalized_value,is_primary,is_verified,consent_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[r.rows[0].id,ch.channel_type,clean(ch.label,50)||null,raw,normalize(raw,ch.channel_type),!!ch.is_primary,!!ch.is_verified,clean(ch.consent_status,20)||'UNKNOWN']);}
 await client.query('COMMIT');await audit(req,'CREATE','contact',r.rows[0].id,{possible_duplicate:duplicate});res.status(201).json({...r.rows[0],possible_duplicate:duplicate});
}catch(e){await client.query('ROLLBACK');console.error(e);res.status(400).json({error:e.code==='23505'?'A similar record already exists or the contact code collided':e.message});}finally{client.release();}});

app.post('/api/contacts/:id/submit',auth,allow('OWNER_ADMIN','DATA_ENTRY'),async(req,res)=>{const r=await pool.query(`UPDATE contacts SET lifecycle_status='PENDING_REVIEW',updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND created_by=$1 AND lifecycle_status='DRAFT' RETURNING id`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(403).json({error:'Draft not found or cannot be submitted'});await audit(req,'SUBMIT','contact',req.params.id);res.json({ok:true});});
app.post('/api/contacts/:id/approve',auth,allow('OWNER_ADMIN'),async(req,res)=>{const r=await pool.query(`UPDATE contacts SET lifecycle_status='APPROVED',owner_user_id=$1,updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND lifecycle_status='PENDING_REVIEW' RETURNING *`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(400).json({error:'Contact is not pending review'});await audit(req,'APPROVE','contact',req.params.id);res.json(r.rows[0]);});
app.post('/api/contacts/:id/return',auth,allow('OWNER_ADMIN'),async(req,res)=>{const comment=clean(req.body?.comment,500);if(!comment)return res.status(400).json({error:'Review comment is required'});try{const r=await pool.query(`UPDATE contacts SET lifecycle_status='DRAFT',updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND lifecycle_status='PENDING_REVIEW' RETURNING id`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(400).json({error:'Contact is not pending review'});await audit(req,'RETURN_FOR_CORRECTION','contact',req.params.id,{comment});res.json({ok:true});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/contacts/:id/activate',auth,allow('OWNER_ADMIN'),async(req,res)=>{try{const r=await pool.query(`UPDATE contacts SET lifecycle_status='ACTIVE',updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND lifecycle_status='APPROVED' RETURNING id`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(400).json({error:'Contact is not approved'});await audit(req,'ACTIVATE','contact',req.params.id);res.json({ok:true});}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/review-queue',auth,allow('OWNER_ADMIN'),async(req,res)=>{try{const r=await pool.query(`SELECT c.id,c.contact_code,c.first_name,c.last_name,c.category,c.priority_code,c.created_at,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.deleted_at IS NULL AND c.lifecycle_status='PENDING_REVIEW' ORDER BY c.created_at ASC`);res.json(r.rows);}catch(e){res.status(500).json({error:'Review queue unavailable'});}});

app.get('/api/contacts/:id',auth,async(req,res)=>{
 try{
  const id=String(req.params.id||'').trim();
  if(!/^[0-9a-fA-F-]{36}$/.test(id)) return res.status(400).json({error:'Invalid contact id'});
  let p;
  if(req.user.role==='OWNER_ADMIN'){
    p=await pool.query(`SELECT c.*,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.id=$1 AND c.deleted_at IS NULL`,[id]);
  }else if(req.user.role==='DATA_ENTRY'){
    p=await pool.query(`SELECT c.*,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.id=$1 AND c.created_by=$2 AND c.lifecycle_status='DRAFT' AND c.deleted_at IS NULL`,[id,req.user.id]);
  }else if(req.user.role==='RESTRICTED_VIEWER'){
    p=await pool.query(`SELECT c.*,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.id=$1 AND c.deleted_at IS NULL AND c.lifecycle_status IN ('APPROVED','ACTIVE','DORMANT') AND (c.visibility_group IS NULL OR EXISTS(SELECT 1 FROM record_access ra WHERE ra.contact_id=c.id AND ra.user_id=$2)) AND (c.is_sensitive=false OR EXISTS(SELECT 1 FROM record_access sra WHERE sra.contact_id=c.id AND sra.user_id=$2))`,[id,req.user.id]);
  }else{
    p=await pool.query(`SELECT c.*,o.name organization FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.id=$1 AND c.deleted_at IS NULL AND c.lifecycle_status IN ('APPROVED','ACTIVE','DORMANT')`,[id]);
  }
  if(!p.rowCount){await audit(req,'UNAUTHORIZED_ACCESS_ATTEMPT','contact',id);return res.status(404).json({error:'Not found'});}
  const c=p.rows[0];
  const ch=await pool.query('SELECT channel_type,label,raw_value,is_primary,consent_status FROM contact_channels WHERE contact_id=$1 ORDER BY is_primary DESC, created_at ASC',[id]);
  const fu=await pool.query(`SELECT id,title,due_at,priority_code,status_code,assigned_to FROM follow_ups WHERE contact_id=$1 AND ($2='OWNER_ADMIN' OR assigned_to=$3) ORDER BY due_at`,[id,req.user.role,req.user.id]);
  let interactions=[];
  if(req.user.role==='OWNER_ADMIN') interactions=(await pool.query(`SELECT i.*,u.full_name created_by_name FROM interactions i JOIN users u ON u.id=i.created_by WHERE i.contact_id=$1 ORDER BY i.occurred_at DESC`,[id])).rows;
  if(req.user.role!=='OWNER_ADMIN'){delete c.marketing_consent;delete c.do_not_contact_reason;delete c.visibility_group;delete c.owner_user_id;delete c.created_by;delete c.updated_by;delete c.deleted_at;delete c.row_version;delete c.photo_path;}
  res.json({contact:c,channels:ch.rows,followUps:fu.rows,interactions});
 }catch(e){console.error('CONTACT PROFILE ERROR:',e.stack||e);res.status(500).json({error:'Contact profile unavailable'});}
});

app.patch('/api/contacts/:id',auth,allow('OWNER_ADMIN'),async(req,res)=>{const x=req.body||{};try{const r=await pool.query(`UPDATE contacts SET first_name=coalesce($1,first_name),last_name=coalesce($2,last_name),preferred_name=coalesce($3,preferred_name),designation=coalesce($4,designation),department=coalesce($5,department),category=coalesce($6,category),subcategory=coalesce($7,subcategory),relationship_status=coalesce($8,relationship_status),priority_code=coalesce($9,priority_code),health_code=coalesce($10,health_code),do_not_contact=coalesce($11,do_not_contact),do_not_contact_reason=coalesce($12,do_not_contact_reason),marketing_consent=coalesce($13,marketing_consent),is_sensitive=coalesce($14,is_sensitive),updated_by=$15,updated_at=now(),row_version=row_version+1 WHERE id=$16 AND deleted_at IS NULL RETURNING *`,[x.first_name,x.last_name,x.preferred_name,x.designation,x.department,x.category,x.subcategory,x.relationship_status,x.priority_code,x.health_code,x.do_not_contact,x.do_not_contact_reason,x.marketing_consent,x.is_sensitive,req.user.id,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Contact not found'});await audit(req,'UPDATE','contact',req.params.id);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/contacts/:id/archive',auth,allow('OWNER_ADMIN'),async(req,res)=>{const r=await pool.query(`UPDATE contacts SET lifecycle_status='ARCHIVED',deleted_at=now(),updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND deleted_at IS NULL RETURNING id`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Contact not found'});await audit(req,'ARCHIVE','contact',req.params.id);res.json({ok:true});});
app.post('/api/contacts/:id/restore',auth,allow('OWNER_ADMIN'),async(req,res)=>{const r=await pool.query(`UPDATE contacts SET lifecycle_status='APPROVED',deleted_at=NULL,updated_by=$1,updated_at=now(),row_version=row_version+1 WHERE id=$2 AND deleted_at IS NOT NULL RETURNING id`,[req.user.id,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Archived contact not found'});await audit(req,'RESTORE','contact',req.params.id);res.json({ok:true});});

app.post('/api/contacts/:id/interactions',auth,allow('OWNER_ADMIN'),async(req,res)=>{const x=req.body||{};const missing=requireFields(x,['subject','channel_code','outcome_code']);if(missing)return res.status(400).json({error:missing});if(!VALID_INTERACTION_CHANNELS.includes(x.channel_code)||!VALID_OUTCOMES.includes(x.outcome_code))return res.status(400).json({error:'Invalid interaction channel or outcome'});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`INSERT INTO interactions(contact_id,occurred_at,channel_code,subject,outcome_code,summary,relationship_status_after,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.params.id,x.occurred_at||new Date(),x.channel_code,clean(x.subject,250),x.outcome_code,clean(x.summary,500)||null,VALID_RELATIONSHIPS.includes(x.relationship_status_after)?x.relationship_status_after:null,req.user.id]);if(clean(x.private_note,5000)){await client.query('INSERT INTO interaction_private_notes(interaction_id,encrypted_note,created_by) VALUES($1,$2,$3)',[r.rows[0].id,encryptNote(clean(x.private_note,5000)),req.user.id]);}const occurredAt = r.rows[0].occurred_at; const nextRelationship = VALID_RELATIONSHIPS.includes(x.relationship_status_after)?x.relationship_status_after:null; const updateSql = nextRelationship ? `UPDATE contacts SET last_interaction_at=$1::timestamptz, relationship_status=$2::varchar, first_connected_at=CASE WHEN first_connected_at IS NULL AND $2::varchar IN ('CONNECTED','COMMUNICATION_STARTED','IN_TOUCH','CONSISTENT_RELATIONSHIP','STRONG_CONNECTION') THEN $1::timestamptz ELSE first_connected_at END, updated_by=$3::uuid, updated_at=now(), row_version=row_version+1 WHERE id=$4::uuid AND deleted_at IS NULL` : `UPDATE contacts SET last_interaction_at=$1::timestamptz, updated_by=$2::uuid, updated_at=now(), row_version=row_version+1 WHERE id=$3::uuid AND deleted_at IS NULL`; const updateParams = nextRelationship ? [occurredAt,nextRelationship,req.user.id,req.params.id] : [occurredAt,req.user.id,req.params.id]; await client.query(updateSql,updateParams);await client.query('COMMIT');await audit(req,'CREATE','interaction',r.rows[0].id);res.status(201).json(r.rows[0]);}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message});}finally{client.release();}});
app.get('/api/interactions/:id/private-note',auth,allow('OWNER_ADMIN'),async(req,res)=>{const r=await pool.query('SELECT encrypted_note FROM interaction_private_notes WHERE interaction_id=$1',[req.params.id]);res.json({private_note:r.rows[0]?decryptNote(r.rows[0].encrypted_note):''});});

app.post('/api/contacts/:id/follow-ups',auth,allow('OWNER_ADMIN','RESTRICTED_VIEWER','MANAGER_VIEWER'),async(req,res)=>{const x=req.body||{};const missing=requireFields(x,['title','due_at']);if(missing)return res.status(400).json({error:missing});if(!VALID_PRIORITIES.includes(x.priority_code||'NORMAL'))return res.status(400).json({error:'Invalid priority'});try{
 const base=contactVisibility(req);const shifted=base.wh.map(v=>v.replace(/\$(\d+)/g,(_,n)=>'$'+(Number(n)+1)));const extra=req.user.role==='OWNER_ADMIN'?'TRUE':'(c.is_sensitive=false OR EXISTS(SELECT 1 FROM record_access sra WHERE sra.contact_id=c.id AND sra.user_id=$2))';const chk=await pool.query(`SELECT c.id FROM contacts c WHERE c.id=$1 AND ${extra} AND ${shifted.join(' AND ')}`,[req.params.id,req.user.id,...base.params]);if(!chk.rowCount)return res.status(403).json({error:'Access denied'});
 const assigned=req.user.role==='OWNER_ADMIN'?(x.assigned_to||req.user.id):req.user.id;const r=await pool.query(`INSERT INTO follow_ups(contact_id,interaction_id,title,description,due_at,remind_at,priority_code,assigned_to,status_code,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'OPEN',$9) RETURNING *`,[req.params.id,x.interaction_id||null,clean(x.title,180),clean(x.description,2000)||null,x.due_at,x.remind_at||null,x.priority_code||'NORMAL',assigned,req.user.id]);await pool.query(`UPDATE contacts SET next_follow_up_at=(SELECT min(due_at) FROM follow_ups WHERE contact_id=$1 AND status_code IN ('OPEN','IN_PROGRESS')),updated_at=now() WHERE id=$1`,[req.params.id]);await audit(req,'CREATE','follow_up',r.rows[0].id);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.patch('/api/follow-ups/:id',auth,async(req,res)=>{const x=req.body||{};if(x.status_code&&!VALID_TASK_STATUS.includes(x.status_code))return res.status(400).json({error:'Invalid task status'});try{const r=await pool.query(`UPDATE follow_ups SET status_code=coalesce($1,status_code),completed_at=case when $1='COMPLETED' then now() when $1 IS NOT NULL AND $1<>'COMPLETED' then NULL else completed_at end,completion_note=coalesce($2,completion_note),updated_at=now() WHERE id=$3 AND (assigned_to=$4 OR $5='OWNER_ADMIN') RETURNING *`,[x.status_code||null,clean(x.completion_note,500)||null,req.params.id,req.user.id,req.user.role]);if(!r.rowCount)return res.status(403).json({error:'Access denied'});await pool.query(`UPDATE contacts SET next_follow_up_at=(SELECT min(due_at) FROM follow_ups WHERE contact_id=$1 AND status_code IN ('OPEN','IN_PROGRESS')),updated_at=now() WHERE id=$1`,[r.rows[0].contact_id]);await audit(req,'UPDATE','follow_up',req.params.id);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/tasks',auth,async(req,res)=>{try{const r=await pool.query(`SELECT f.id,f.title,f.description,f.due_at,f.priority_code,f.status_code,f.contact_id,c.contact_code,c.first_name,c.last_name FROM follow_ups f JOIN contacts c ON c.id=f.contact_id WHERE f.assigned_to=$1 AND c.deleted_at IS NULL AND f.status_code IN ('OPEN','IN_PROGRESS') ORDER BY f.due_at ASC LIMIT 200`,[req.user.id]);res.json(r.rows);}catch(e){res.status(500).json({error:'Tasks unavailable'});}});

app.get('/api/users',auth,allow('OWNER_ADMIN'),async(req,res)=>res.json((await pool.query('SELECT id,email,full_name,role_code,is_active,created_at FROM users ORDER BY created_at')).rows));
app.post('/api/users',auth,allow('OWNER_ADMIN'),async(req,res)=>{const {email,password,full_name,role_code}=req.body||{};if(!email||!password||!full_name||!VALID_ROLES.includes(role_code)||role_code==='OWNER_ADMIN')return res.status(400).json({error:'Valid name, email, password and non-owner role are required'});try{const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO users(email,password_hash,full_name,role_code) VALUES($1,$2,$3,$4) RETURNING id,email,full_name,role_code,is_active',[email.trim().toLowerCase(),hash,clean(full_name,150),role_code]);await audit(req,'CREATE','user',r.rows[0].id);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.code==='23505'?'Email already exists':e.message});}});
app.patch('/api/users/:id/status',auth,allow('OWNER_ADMIN'),async(req,res)=>{if(req.params.id===req.user.id)return res.status(400).json({error:'You cannot deactivate your own account'});const r=await pool.query('UPDATE users SET is_active=$1 WHERE id=$2 RETURNING id,email,full_name,role_code,is_active',[!!req.body.is_active,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'User not found'});await audit(req,'UPDATE_STATUS','user',req.params.id);res.json(r.rows[0]);});
app.get('/api/audit-events',auth,allow('OWNER_ADMIN'),async(req,res)=>res.json((await pool.query(`SELECT a.*,u.full_name actor_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 200`)).rows));
app.get('/api/export/contacts.csv',auth,allow('OWNER_ADMIN'),async(req,res)=>{try{const r=await pool.query(`SELECT c.contact_code,c.first_name,c.last_name,c.preferred_name,o.name organization,c.designation,c.category,c.subcategory,c.priority_code,c.relationship_status,c.lifecycle_status,c.marketing_consent,c.do_not_contact,c.created_at,c.updated_at FROM contacts c LEFT JOIN organizations o ON o.id=c.organization_id WHERE c.deleted_at IS NULL ORDER BY c.created_at DESC`);const headers=['contact_code','first_name','last_name','preferred_name','organization','designation','category','subcategory','priority_code','relationship_status','lifecycle_status','marketing_consent','do_not_contact','created_at','updated_at'];const csv=[headers.join(','),...r.rows.map(x=>headers.map(h=>csvCell(x[h])).join(','))].join('\n');await audit(req,'EXPORT','contact',null,{row_count:r.rowCount,format:'csv'});res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="private-contact-crm-export.csv"');res.send(csv);}catch(e){res.status(500).json({error:'Export unavailable'});}});
app.post('/api/import/contacts/preview',auth,allow('OWNER_ADMIN'),upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'CSV file required'});try{const text=fs.readFileSync(req.file.path,'utf8');const rows=csvParse(text);if(rows.length<2)return res.status(400).json({error:'CSV has no data rows'});const headers=rows[0].map(x=>x.trim());const required=['first_name','category'];const missing=required.filter(x=>!headers.includes(x));if(missing)return res.status(400).json({error:'Missing columns: '+missing.join(', ')});const preview=rows.slice(1,101).map((r,i)=>Object.fromEntries(headers.map((h,j)=>[h,r[j]||''])));fs.unlink(req.file.path,()=>{});res.json({row_count:rows.length-1,headers,preview});}catch(e){res.status(400).json({error:'Invalid CSV'});}});

app.post('/api/import/contacts/commit',auth,allow('OWNER_ADMIN'),async(req,res)=>{const rows=Array.isArray(req.body?.rows)?req.body.rows.slice(0,1000):[];if(!rows.length)return res.status(400).json({error:'No previewed rows to import'});let created=0,skipped=0;const errors=[];for(const x of rows){try{const first=clean(x.first_name,100);const category=clean(x.category,100);if(!first||!category){skipped++;continue;}const channels=[];if(x.mobile)channels.push({type:'MOBILE',value:clean(x.mobile,300)});if(x.email)channels.push({type:'EMAIL',value:clean(x.email,300)});if(x.whatsapp)channels.push({type:'WHATSAPP',value:clean(x.whatsapp,300)});let duplicate=false;if(channels.length){const vals=channels.map(ch=>normalize(ch.value,ch.type));duplicate=!!(await pool.query(`SELECT 1 FROM contact_channels cc JOIN contacts c ON c.id=cc.contact_id WHERE c.deleted_at IS NULL AND cc.normalized_value=ANY($1::text[]) LIMIT 1`,[vals])).rowCount;}if(duplicate){skipped++;continue;}const client=await pool.connect();try{await client.query('BEGIN');let orgId=null;if(x.organization){const o=await client.query('SELECT id FROM organizations WHERE lower(name)=lower($1) LIMIT 1',[clean(x.organization,200)]);orgId=o.rowCount?o.rows[0].id:(await client.query('INSERT INTO organizations(name) VALUES($1) RETURNING id',[clean(x.organization,200)])).rows[0].id;}const code='CT-'+new Date().getFullYear()+'-'+crypto.randomInt(100000,999999);const r=await client.query(`INSERT INTO contacts(contact_code,first_name,last_name,designation,category,subcategory,tags,source_code,source_detail,organization_id,owner_user_id,is_sensitive,relationship_status,priority_code,lifecycle_status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'IMPORT',$8,$9,$10,false,'NOT_CONTACTED',$11,'DRAFT',$12) RETURNING id`,[code,first,clean(x.last_name,100)||null,clean(x.designation,150)||null,category,clean(x.subcategory,100)||null,[],clean(x.source_detail,250)||'CSV import',orgId,req.user.id,VALID_PRIORITIES.includes(x.priority_code)?x.priority_code:'NORMAL',req.user.id]);for(const ch of channels)await client.query('INSERT INTO contact_channels(contact_id,channel_type,raw_value,normalized_value,is_primary) VALUES($1,$2,$3,$4,$5)',[r.rows[0].id,ch.type,ch.value,normalize(ch.value,ch.type),true]);await client.query('COMMIT');created++;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}catch(e){skipped++;errors.push(String(e.message).slice(0,200));}}await audit(req,'IMPORT','contact',null,{created,skipped});res.json({created,skipped,errors:errors.slice(0,20)});});

app.post('/api/attachments',auth,allow('OWNER_ADMIN','DATA_ENTRY'),upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'File required'});await audit(req,'UPLOAD','attachment',null,{filename:req.file.originalname});res.json({ok:true,filename:req.file.originalname,storage_path:req.file.path});});

app.use('/api',(req,res)=>res.status(404).json({error:'API endpoint not found'}));
app.use(express.static(path.join(__dirname,'..','client')));
app.get(/.*/, (req,res)=>res.sendFile(path.join(__dirname,'..','client','index.html')));

init().then(()=>app.listen(PORT,()=>console.log(`Private Contact CRM running on http://localhost:${PORT}`))).catch(e=>{console.error('Startup failed:',e.message);process.exit(1);});
process.on('SIGINT',async()=>{await pool.end();process.exit(0);});
process.on('SIGTERM',async()=>{await pool.end();process.exit(0);});
